config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:create, :index, :new, :destroy, :show]
  resources :listings
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  root 'users#show'
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  post '/users/:id' => 'users#update', as: 'user_update'

   get "/auth/:provider/callback" => "sessions#create_from_omniauth"

   post "/fetch_tags" => 'listings#from_category', as: 'fetch_tags'

   post "/like_results" => 'listings#like_results', as: 'like_results'
  get "/users/:id/edit_user" => 'users#edit_profile', as: 'edit_user'

    resources :users, only: [:show, :edit, :update, :destroy] 
    resources :reservations, only: [:create,:show]

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	has_many :tags, through: :categories
	has_many :categories, dependent: :destroy
	has_many :reservations, dependent: :destroy
	belongs_to :user
	scope :featured, -> {order('reservations_count ASC')}
	mount_uploaders :avatars, AvatarUploader
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:edit, :update, :destroy, :show]
  def index 
    @listing=Listing.all
    @tag=Tag.new 
    @search = Listing.new

  end

  def new
    @listing = Listing.new
    @tags = @listing.tags.new
  end
 
  def create

    @listing = current_user.listings.new(listing_params)
    @listing.available_dates = []
    (Date.parse(params[:listing][:available_dates][:start_date])..Date.parse(params[:listing][:available_dates][:end_date])).each do |d|
      @listing.available_dates << d
    end
    if @listing.save
      @tag=params[:listing][:tag][:tag].downcase.split(",") 
      @listing
      @tag.each{|x| x.gsub!(" ","")}
      @tag.uniq.each do |name|
        @listing.tags.find_or_create_by(tag:name)
      end
      redirect_to listing_path(@listing.id)
    else
      render :new
    end
  end

  def show
    @reservations=Reservation.where(listing_id:@listing.id)
    @reservation=Reservation.new
  end

  def edit
  end

  def update

    @listing.update(listing_params)

    temp =[]
    r_period = []
    Reservation.where(listing_id:@listing.id).each do |r|
      (r.start_date..r.end_date).each do |d|
        temp << d
      end
      r_period = r_period + temp
    end

    control=@listing.available_dates
    (Date.parse(params[:listing][:available_dates][:start_date])..Date.parse(params[:listing][:available_dates][:end_date])).each do |d|
        if !r_period.include? d
          if @listing.available_dates.include? d
            @listing.available_dates=@listing.available_dates-Array(d)
          else
            @listing.available_dates=@listing.available_dates+Array(d)
          end
        else
          @listing.available_dates = control
          break   
        end
      end
      @listing.save


      redirect_to listing_path(@listing.id)
  end

  def destroy
    @listing.delete
    redirect_to listings_path
  end

  def from_category
    # params[:tag[:tag]].downcase.split(",")
    input = params[:tag][:tag].downcase.split(",")

    input.each {|i| i.gsub!(" ","")}
    @listing = []
    input.uniq.each do |i|

          return @listing = [] if Tag.find_by_tag(i) == nil
          next @listing = Array(Tag.find_by_tag(i).listings) if @listing= []
          @listing=@listing & Array(Tag.find_by_tag(i).listings)
    end

    respond_to do |format|
        format.js
    end
  end

  def like_results
    @listing=[]
    Listing.all.each do |l|
      @listing=@listing + Array(l) if l.locations.match("#{params[:listing][:locations]}") != nil
    end

    respond_to do |format|
        format.js
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:locations,:prices,:num_of_rooms,:num_of_guests,{avatars:[]})
  end
  def set_listing
    @listing = Listing.find(params[:id]) 
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form.file_field :avatars, multiple: true %>

app/views/listings/_listing_list.html.erb
<%@listing.each do |listing|%>
<%=link_to "#{listing.locations}",listing_path(listing.id) %>  <%=listing.prices%>  
<%listing.tags.each do |tag|%>
<%=link_to "#{tag.tag}", tag_path(tag.id)%> 
<%end%>
 <%= link_to 'edit listings',edit_listing_path(listing.id)%><br>
<%end%>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/destroy.html.erb
<h1>Listings#destroy</h1>
<p>Find me in app/views/listings/destroy.html.erb</p>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

  <%= form_for @listing, :html => {:multipart => true} do |f| %>
  	<%= f.text_field :locations ,:value => 'location' %>
  	<%= f.number_field :prices %>
   	<%=  f.fields_for :available_dates do |form|%>
	  	<%= form.text_field :start_date, :data =>{ :provide =>"datepicker"}%>
	  	<%= form.text_field :end_date, :data =>{ :provide =>"datepicker"}%>
  	<%end%>
  	<%= render partial: '/listings/form', object: f%>
  	<%= f.submit "Update" %>
  	<%end%>

app/views/listings/from_category.js.erb
$('#list').html("<%= escape_javascript(
		render partial: 'listing_list'
		) 
	%>"); 

app/views/listings/index.html.erb
<h1>Listings#index</h1>
<p>Find me in app/views/listings/index.html.erb</p>

<%= form_for @tag do |t| %>
<%= t.text_field :tag ,:value => 'filter' %>
<%end%>
<h2>Tag selection</h2>
<%Tag.all.each do |t|%>
<%="#{t.tag}, "%>
<%end%>
<br>
<br>
<div id = "advance"> Advance Search</div>
<div id = "search" style = "display:none">
	<%= form_for @search do |l| %> 
		<%= l.check_box("locations")%><br>
		<!-- checkbox to determine field to check for like -->
		<%= l.text_field :locations, :value => "locations"%> 
		<%end%>
</div>

<div id=list><%= render 'listing_list' %></div>

app/views/listings/new.html.erb
<h1>Listings#new</h1>


  <%= form_for @listing do |f| %>
  	<%= f.text_field :locations ,:value => 'location' %>
  	<%= f.number_field :prices %>
  	<%=  f.fields_for @tags do |form|%>
	  	<%= form.text_field :tag, :value => 'tag,tag,tag'%>
  	<%end%>
   	<%=  f.fields_for :available_dates do |form|%>
	  	<%= form.text_field :start_date, :data =>{ :provide =>"datepicker"}%>
	  	<%= form.text_field :end_date, :data =>{ :provide =>"datepicker"}%>
  	<%end%>

  	<%= f.submit "Create" %>
  	<%end%>

app/views/listings/show.html.erb
<h1 class='t'>Listings#show</h1>
<p>Find me in app/views/listings/show.html.erb</p>



<%=link_to "All Listings", listings_path%><br>

<%@listing.tags.each do |t|%>
<%=link_to "#{t.tag}", tag_path(t.id)%>
<%end%>

<%= link_to "Delete", @listing, method: :delete%>

<%= image_tag (@listing.avatars[0].large.url) if @listing.avatars != [] %>

<%= image_tag (@listing.avatars[1].large.url) if @listing.avatars != [] %>

<%= image_tag (@listing.avatars[2].large.url) if @listing.avatars != [] %>

<h2>Book Now!</h2> 

<h3>Current Reservations:</h3>
<br>
<%@reservations.each do |r|%>

<%= r.start_date %>-<%=r.end_date%> BY <%=r.user.email%> <%= link_to "Details", reservation_path(r.id)%> <br>
<%end%>
<br>
<%= content_tag :div, nil, id: "available_dates", data: {dates: @listing.available_dates} %>

<%= form_for @reservation do |f| %> 
<%= f.text_field :start_date, :data =>{ :provide =>"datepicker"}%>
<%= f.text_field :end_date, :data =>{ :provide =>"datepicker"}%>
<%= f.hidden_field :listing_id, value: @listing.id%>
<%= f.submit "Book"%>
<%end%>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>