config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:create, :index, :new, :destroy, :show]
  resources :listings
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  root 'users#show'
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  post '/users/:id' => 'users#update', as: 'user_update'

   get "/auth/:provider/callback" => "sessions#create_from_omniauth"

   post "/fetch_tags" => 'listings#from_category', as: 'fetch_tags'

   post "/like_results" => 'listings#like_results', as: 'like_results'
  get "/users/:id/edit_user" => 'users#edit_profile', as: 'edit_user'

    resources :users, only: [:show, :edit, :update, :destroy] 
    resources :reservations, only: [:create,:show]

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
    has_many :authentications, :dependent => :destroy
    has_many :listings 
    has_many :reservations
    mount_uploaders :avatars, AvatarUploader
  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.first_name = auth_hash["info"]["first_name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.authentications<<(authentication)
      u.encrypted_password= SecureRandom.hex(5)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

  include Clearance::User
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@featured_listings = Listing.featured
		@listings=@featured_listings.page params[:page]
	end

	def edit
	end

	def edit_profile
		@user=current_user
	end

	def update
		@user=current_user

		@user.update(user_params)
		redirect_to edit_user_path(current_user.id)
	end


  private

  def user_params
    params.require(:user).permit(:email,{avatars:[]})
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/edit_profile.html.erb
<%= form_for @user, :html => {:mutipart => true} do |u|%>
	<%= u.file_field :avatars, multiple: true %>
  	<%= u.submit "Update" %>
  	<%end%>

  	<%= image_tag (@user.avatars[0].large.url) if @user.avatars != [] %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= link_to 'new listing', new_listing_path%>
<%= link_to 'all listings',listings_path%>


<% if signed_in? %>
	<%= link_to 'edit profile',edit_user_path(current_user.id)%>
	<h1>Reservations</h1>
	<%Reservation.where(user_id:current_user.id).each do |r|%>
	<%= Listing.find(r.listing_id).locations%>  <%= r.start_date%>   <%= r.end_date%> <br>
	<%end%>
<%end%>
<br>
<h1>Listings</h1>
<%@listings.each do |x|%>
	<%=x.locations%><br>
<%end%>
<%= paginate @listings %>