config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:create, :index, :new, :destroy, :show]
  resources :listings
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  root 'users#show'
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  post '/users/:id' => 'users#update', as: 'user_update'

   get "/auth/:provider/callback" => "sessions#create_from_omniauth"

   post "/fetch_tags" => 'listings#from_category', as: 'fetch_tags'

   post "/like_results" => 'listings#like_results', as: 'like_results'
  get "/users/:id/edit_user" => 'users#edit_profile', as: 'edit_user'

    resources :users, only: [:show, :edit, :update, :destroy] 
    resources :reservations, only: [:create,:show]

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :listings, through: :categories
	has_many :categories, dependent: :destroy
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:destroy, :show]
  def index
    @tag= Tag.all
  end

  def edit
    @tag= Tag.new
  end

  def update
    @tag = Tag.new(tag_params)
    if @tag.save
    else
    end
  end

  def show
    @list=@tag.listings
  end

  def destroy
    @tag.delete

  end

  private
  def tag_params
    params.require(:tag).permit(:tag)
  end
  def set_tag
    @tag = Tag.find(params[:id]) 
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

app/views/tags/index.html.erb
<h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

<%@tag.each do |t|%>
<%=link_to "#{t.tag}",tag_path(t.id)%><br>
<%end%>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

<%=link_to "All Tags", tags_path%><br>

<%@list.each do |l|%>

<%=link_to "#{l.locations}",listing_path(l.id)%><br>

<%end%>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>