config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:create, :index, :new, :destroy, :show]
  resources :listings
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  root 'users#show'
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  post '/users/:id' => 'users#update', as: 'user_update'

   get "/auth/:provider/callback" => "sessions#create_from_omniauth"

   post "/fetch_tags" => 'listings#from_category', as: 'fetch_tags'

   post "/like_results" => 'listings#like_results', as: 'like_results'
  get "/users/:id/edit_user" => 'users#edit_profile', as: 'edit_user'

    resources :users, only: [:show, :edit, :update, :destroy] 
    resources :reservations, only: [:create,:show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tag %>


</head>
<body>
  <div id="header">
    <% if signed_in? -%>
   	Signed in as: <%= current_user.email%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>